service: example-serverless
frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x

functions:
  http-router:
    handler: bin/http
    timeout: 30
    package:
      include:
        - bin/http
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true

package:
  exclude:
    - ./**
  include:
    - ./bin/**